version: '3'

services:

  frontend:
    build: ./zmartr-frontend
    ports:
      - '3000:3000'
    working_dir: /usr/src/app
    volumes:
      - ./zmartr-frontend:/usr/src/app
      - /usr/src/app/node_modules
    command: 'npm start'
  api:
    build: ./zmartr-api
    restart: always
    working_dir: /usr/src/app
    volumes:
      - ./zmartr-api:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '5000:5000'
    command: 'npm run start:watch'

  tasks:
    build: ./zmartr-tasks
    restart: always
    environment: 
      MONGO_HOST: 'tasks-db'
    working_dir: /usr/src/app
    volumes:
      - ./zmartr-tasks:/usr/src/app/
      - /usr/src/app/node_modules
    command: 'npm start'
    depends_on: 
      - 'tasks-db'
  tasks-db:
    image: mongo
    restart: always
    volumes: 
      - './data/tasks:/data/db'

  users:
    build: ./zmartr-users
    restart: always
    environment: 
      MONGO_HOST: 'users-db'
    working_dir: /usr/src/app
    volumes:
      - ./zmartr-users:/usr/src/app/
      - /usr/src/app/node_modules
    command: 'npm start'
    depends_on: 
      - 'users-db'
  users-db:
    image: mongo
    restart: always
    volumes: 
      - './data/users:/data/db'