apiVersion: apps/v1
kind: Deployment
metadata:
  name: zmartr-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zmartr-api
  template:
    metadata:
      labels:
        app: zmartr-api
    spec:
      containers:
      - name: zmartr-api
        image: registry.digitalocean.com/oscarleo/zmartr-api
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        ports:
        - containerPort: 5000
        env:
        - name: TASKS_MICROSERVICE
          value: 'zmartr-tasks-cluster-ip'
