apiVersion: apps/v1
kind: Deployment
metadata:
  name: zmartr-tasks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zmartr-tasks
  template:
    metadata:
      labels:
        app: zmartr-tasks
    spec:
      containers:
      - name: zmartr-tasks
        image: registry.digitalocean.com/oscarleo/zmartr-tasks
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        ports:
        - containerPort: 80
        env:
        - name: MONGO_USERNAME
          value: "dcrowd"
        - name: MONGO_PASSWORD
          value: "Wuc0IlUXzxBCEpTK"
