apiVersion: apps/v1
kind: Deployment
metadata:
  name: zmartr-users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zmartr-users
  template:
    metadata:
      labels:
        app: zmartr-users
    spec:
      containers:
      - name: zmartr-users
        image: zmartr/users
        imagePullPolicy: "Never"
        resources:
          requests:
            memory: "64Mi"
            cpu: "125m"
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 80
        env:
        - name: MONGO_USERNAME
          value: "dcrowd"
        - name: MONGO_PASSWORD
          value: "Wuc0IlUXzxBCEpTK"
