name: Docker

on:
  push:
    branches: [ master ]

jobs:
  build_frontend:
    runs-on: ubuntu-latest
    name: 'Building Zmartr Frontend'
    steps:
      - name: Installing doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Login to registry
        run: doctl registry login
      - name: Getting source-code
        uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          repository: registry.digitalocean.com/oscarleo
          path: ./zmartr-frontend

