name: Docker

on:
  push:
    branches: [ master ]

jobs:
  build_frontend:
    runs-on: ubuntu-latest
    name: 'Building Zmartr Frontend'
    steps:
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - uses: actions/checkout@v2
